[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Kitworks API"
authors = [{name = "Volodymyr Karabanov", email = "vk@kitworks.systems"}]
dynamic = ["version", "description"]
